[package]
name = "vitrail-rs"
version = "0.1.0"
authors = ["illis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_seeder = "0.2.1"
rand_pcg = "0.2.1"
serde_json = "1.0"